openapi: 3.0.3
info:
  version: 1.0.0
  title: Template API-spec

security:
  - bearerAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/schedules:
    get:
      operationId: listSchedules
      summary: List schedules.
      description: Lists schedules.
      tags:
        - Schedules
      parameters:
        - name: firstResult
          in: query
          description: First result. Defaults to 0
          schema:
            type: integer
        - name: maxResults
          in: query
          description: Max results. Defaults to 10
          schema:
            type: integer
        - name: startDate
          in: query
          description: From which date onwards the search is made. Includes the given date
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: Until which date the search is made. Includes the given date
          schema:
            type: string
            format: date
      responses:
        "200":
          description: List of schedules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Schedule"
          headers:
            X-Total-Count:
              schema:
                type: integer
                format: int64
              description: Total count of schedules with given filters.
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createSchedule
      summary: Create an schedule.
      description: Creates a new schedule.
      tags:
        - Schedules
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Schedule"
        description: Payload
        required: true
      responses:
        "200":
          description: Created Schedule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/v1/schedules/{scheduleId}":
    get:
      operationId: findSchedule
      summary: Find a schedule.
      description: Finds a schedule by id.
      tags:
        - Schedules
      parameters:
        - name: scheduleId
          required: true
          in: path
          description: schedule id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Schedule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateSchedule
      summary: Update a schedule.
      description: Updates a schedule
      tags:
        - Schedules
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Schedule"
        description: Payload
        required: true
      parameters:
        - name: scheduleId
          required: true
          in: path
          description: schedule id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Updated Schedule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: deleteSchedule
      summary: Delete a schedule.
      description: Deletes a schedule.
      tags:
        - Schedules
      parameters:
        - name: scheduleId
          required: true
          in: path
          description: schedule id
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Success
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Schedule:
      type: object
      description: Schedule object
      required:
        - date
        - images
        - color
        - staff
        - metadata
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Schedule Id in UUID format
        date:
          type: string
          format: date
          description: Schedule date
        images:
          $ref: "#/components/schemas/ScheduleImages"
        color:
          type: string
          description: Color for this schedule
        staff:
          $ref: "#/components/schemas/Staff"
        metadata:
          $ref: "#/components/schemas/Metadata"

    ScheduleImages:
      type: object
      description: Schedule images object
      required:
        - dayOfTheWeek
        - date
        - month
        - season
        - year
        - events
      properties:
        dayOfTheWeek:
          type: string
          format: uri
          description: Image of the day of the week
        date:
          type: string
          format: uri
          description: Image of the date
        month:
          type: string
          format: uri
          description: Image of the month
        season:
          type: string
          format: uri
          description: Image of the season
        year:
          type: string
          format: uri
          description: Image of the year
        holiday:
          type: string
          format: uri
          description: Image of the holiday
        events:
          type: array
          items:
            type: string
            format: uri
          description: List of event image URI's

    Staff:
      type: object
      description: Staff object
      required:
        - scheduleId
        - morningShift
        - eveningShift
        - nightShift
      properties:
        scheduleId:
          type: string
          format: uuid
          readOnly: true
        morningShift:
          type: array
          description: List of image uri's of staff members for morning shift
          items:
            type: string
            format: uri
        eveningShift:
          type: array
          description: List of image uri's of staff members for evening shift
          items:
            type: string
            format: uri
        nightShift:
          type: array
          description: List of image uri's of staff members for night shift
          items:
            type: string
            format: uri

    Metadata:
      type: object
      description: Metadata object
      required:
        - creatorId
        - lastModifierId
        - createdAt
        - modifiedAt
      properties:
        creatorId:
          description: Id of creator
          type: string
          format: uuid
          readOnly: true
        lastModifierId:
          description: Id of last modifier
          type: string
          format: uuid
          readOnly: true
        createdAt:
          type: string
          format: date-time
          description: Created date
          readOnly: true
        modifiedAt:
          type: string
          format: date-time
          description: Date modified
          readOnly: true